### ISSUE TITLE
where the 'vocab.dict'?

### ISSUE THREAD

**Issue by Circlechy** [renll/StateNet#1]
Thanks for you code.
        Could you release the 'vocab.dict' file, which needed in data.py, I can't find it in the source. And the json files 'train_nbest.json' ,'train_nbest_tagged.json' are created by data.py?

**Comment by renll** [comment]
You actually do not need the 'vocab.dict' file. The json files should be created by mat_data.py, which uses the vocab files in the source.

**Comment by Circlechy** [comment]
@renll Thanks for your help, I generated the json files successfully. But I have another question when I run the code, can't find the file 'embed_vN3.npy', What should I do with it? >*-*<

**Comment by renll** [comment]
You can generate it through the file get_embedding.py, which needs the pretrained paragram_sl999 embedding.

**Comment by Circlechy** [comment]
Thanks for your kind reply !
